language: python
python:
  - 2.7
before_install:
  - pip install coveralls
  - sudo apt-get install -qq libxml2-dev libxslt-dev
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
install:
  - ./bootstrap.sh
  - bin/buildout -t 5 -Nq
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/test
